export const initialValues = {
    firstName: "",
    lastName: "",
    age: "",
    phone: "",
    discord: "",
    email: "",
    familiar: "",
    current_job: "",
    yourself: "",
    join_us: [],
    willAdd: "",
    practice: "",
    experiences: "",
    english: "",
    voucher: "",
    mental: "",
    youtube: "",
    twitch: "",
    instagram: "",
    twitter: "",
}